# Generated by Django 5.0.6 on 2024-06-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='like',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
